/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "inverse-on-surface": "#313030",
                "on-secondary": "#2f3131",
                "on-tertiary-fixed-variant": "#544600",
                "secondary-container": "#454747",
                "on-secondary-fixed": "#1a1c1c",
                "surface-container-lowest": "#0e0e0e",
                "surface-tint": "#e60012",
                "inverse-surface": "#e5e2e1",
                "on-primary-fixed": "#ffffff",
                "on-primary-container": "#ffffff",
                "error": "#e60012",
                "primary-fixed-dim": "#e60012",
                "on-surface-variant": "#e9bcb6",
                "on-background": "#ffffff",
                "tertiary-container": "#c9a900",
                "on-secondary-container": "#b4b5b5",
                "on-tertiary-container": "#4c3f00",
                "surface-bright": "#3a3939",
                "on-primary": "#ffffff",
                "surface-container-high": "#2a2a2a",
                "surface": "#131313",
                "background": "#131313",
                "secondary-fixed-dim": "#c6c6c7",
                "tertiary": "#e9c400",
                "on-surface": "#ffffff",
                "on-error": "#ffffff",
                "surface-variant": "#353534",
                "secondary-fixed": "#e2e2e2",
                "secondary": "#c6c6c7",
                "outline-variant": "#5f3f3b",
                "tertiary-fixed": "#ffe16d",
                "tertiary-fixed-dim": "#e9c400",
                "on-tertiary-fixed": "#221b00",
                "on-tertiary": "#3a3000",
                "primary-container": "#e60012",
                "outline": "#af8782",
                "surface-dim": "#131313",
                "inverse-primary": "#c0000d",
                "surface-container-highest": "#353534",
                "on-primary-fixed-variant": "#ffffff",
                "surface-container": "#201f1f",
                "on-error-container": "#ffffff",
                "error-container": "#93000a",
                "on-secondary-fixed-variant": "#454747",
                "primary": "#e60012",
                "surface-container-low": "#1c1b1b",
                "primary-fixed": "#e60012",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                gutter: "24px",
                base: "8px",
                "margin-desktop": "64px",
                "margin-mobile": "16px",
            },
            fontFamily: {
                "section-title": ["Bricolage Grotesque", "sans-serif"],
                "label-caps": ["Archivo Narrow", "sans-serif"],
                "headline-lg": ["Anton", "sans-serif"],
                "headline-xl": ["Anton", "sans-serif"],
                "body-lg": ["Archivo Narrow", "sans-serif"],
                "headline-lg-mobile": ["Anton", "sans-serif"],
                "body-md": ["Archivo Narrow", "sans-serif"],
            },
            fontSize: {
                "section-title": [
                    "24px",
                    {
                        lineHeight: "32px",
                        fontWeight: "800",
                    },
                ],
                "label-caps": [
                    "12px",
                    {
                        lineHeight: "16px",
                        letterSpacing: "0.1em",
                        fontWeight: "700",
                    },
                ],
                "headline-lg": [
                    "48px",
                    {
                        lineHeight: "48px",
                        letterSpacing: "-0.02em",
                        fontWeight: "400",
                    },
                ],
                "headline-xl": [
                    "80px",
                    {
                        lineHeight: "80px",
                        letterSpacing: "-0.04em",
                        fontWeight: "400",
                    },
                ],
                "body-lg": [
                    "18px",
                    {
                        lineHeight: "28px",
                        letterSpacing: "0.01em",
                        fontWeight: "500",
                    },
                ],
                "headline-lg-mobile": [
                    "36px",
                    {
                        lineHeight: "36px",
                        fontWeight: "400",
                    },
                ],
                "body-md": [
                    "16px",
                    {
                        lineHeight: "24px",
                        fontWeight: "400",
                    },
                ],
            },
        },
    },
    plugins: [],
};
